package interface_adapters.StartScreen;

public class StartScreenState {
    private String pin = "";
    private String username = "";
    private String errorMessage = "";
    // Couldn't think of a better name, but it's the autogenerated pin from 'start session'
    private String createdSessionPin = "";

    public StartScreenState() {}

    public String getPin(){
        return pin;
    }

    public void setPin(String pin){
        this.pin = pin;
    }

    public String getUsername(){
        return username;
    }

    public void setUsername(String username){
        this.username = username;
    }

    public String getErrorMessage(){
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage){
        this.errorMessage = errorMessage;
    }

    public String getCreatedSessionPin(){
        return createdSessionPin;
    }

    public void setCreatedSessionPin(String createdSessionPin){
        this.createdSessionPin = createdSessionPin;
    }

}
